import type { AgentWorkbenchRunViewModel } from "./view-model";

export const agentWorkbenchFixtureQuery =
  "核验这条 AI 教育事件的可靠证据，并说明品牌表达边界。";

export const agentWorkbenchFixtureRun: AgentWorkbenchRunViewModel = {
  runId: "00000000-0000-4000-8000-000000000901",
  status: "completed",
  statusLabel: "分析已完成",
  errorCode: null,
  summary: "两条已治理证据支持该事件，品牌资料仅用于调整表达。",
  claims: [
    {
      id: "claim-1",
      text: "教育主管部门已发布相关公开说明。",
      kind: "external_fact",
      kindLabel: "外部事实",
      citationIds: ["evidence-1"],
    },
    {
      id: "claim-2",
      text: "面向家长的表达应保持准确、克制，并明确证据边界。",
      kind: "brand_statement",
      kindLabel: "品牌表达",
      citationIds: ["brand-1"],
    },
  ],
  citations: [
    {
      id: "evidence-1",
      kind: "evidence",
      kindLabel: "事实证据",
      sourceName: "教育主管部门",
      title: "人工智能教育应用公开说明",
      url: "https://example.edu.cn/policy/ai-education",
      evidenceEligible: true,
    },
    {
      id: "brand-1",
      kind: "brand_context",
      kindLabel: "品牌上下文",
      sourceName: "脱敏品牌规范",
      title: "家长沟通语气",
      url: null,
      evidenceEligible: false,
    },
  ],
  steps: [
    {
      id: "step-1",
      ordinal: 1,
      kind: "model_decision",
      kindLabel: "模型决策",
      status: "succeeded",
      statusLabel: "已完成",
      code: null,
      toolName: null,
      toolLabel: null,
      displayLabel: "选择下一步安全动作",
      durationMs: 42,
      details: [{ label: "模式", value: "离线确定性策略" }],
      citationIds: [],
    },
    {
      id: "step-2",
      ordinal: 2,
      kind: "tool_call",
      kindLabel: "工具调用",
      status: "succeeded",
      statusLabel: "已完成",
      code: null,
      toolName: "search_evidence",
      toolLabel: "检索事实证据",
      displayLabel: "调用：检索事实证据",
      durationMs: 0,
      details: [
        { label: "查询长度", value: "28" },
        { label: "请求上限", value: "3" },
      ],
      citationIds: [],
    },
    {
      id: "step-3",
      ordinal: 3,
      kind: "tool_result",
      kindLabel: "工具观察",
      status: "succeeded",
      statusLabel: "已完成",
      code: null,
      toolName: "search_evidence",
      toolLabel: "检索事实证据",
      displayLabel: "观察：检索事实证据",
      durationMs: 18,
      details: [{ label: "结果数量", value: "2 条" }],
      citationIds: ["evidence-1"],
    },
    {
      id: "step-4",
      ordinal: 4,
      kind: "model_decision",
      kindLabel: "模型决策",
      status: "succeeded",
      statusLabel: "已完成",
      code: null,
      toolName: null,
      toolLabel: null,
      displayLabel: "选择下一步安全动作",
      durationMs: 36,
      details: [{ label: "模式", value: "离线确定性策略" }],
      citationIds: [],
    },
    {
      id: "step-5",
      ordinal: 5,
      kind: "tool_call",
      kindLabel: "工具调用",
      status: "succeeded",
      statusLabel: "已完成",
      code: null,
      toolName: "retrieve_brand_context",
      toolLabel: "召回品牌上下文",
      displayLabel: "调用：召回品牌上下文",
      durationMs: 0,
      details: [
        { label: "查询长度", value: "28" },
        { label: "受众", value: "parents" },
      ],
      citationIds: [],
    },
    {
      id: "step-6",
      ordinal: 6,
      kind: "tool_result",
      kindLabel: "工具观察",
      status: "succeeded",
      statusLabel: "已完成",
      code: null,
      toolName: "retrieve_brand_context",
      toolLabel: "召回品牌上下文",
      displayLabel: "观察：召回品牌上下文",
      durationMs: 11,
      details: [{ label: "结果数量", value: "1 条" }],
      citationIds: ["brand-1"],
    },
    {
      id: "step-7",
      ordinal: 7,
      kind: "model_decision",
      kindLabel: "模型决策",
      status: "succeeded",
      statusLabel: "已完成",
      code: null,
      toolName: null,
      toolLabel: null,
      displayLabel: "形成引用结论",
      durationMs: 201,
      details: [{ label: "模式", value: "离线确定性策略" }],
      citationIds: [],
    },
    {
      id: "step-8",
      ordinal: 8,
      kind: "final",
      kindLabel: "最终输出",
      status: "succeeded",
      statusLabel: "引用校验通过",
      code: null,
      toolName: null,
      toolLabel: null,
      displayLabel: "形成引用结论",
      durationMs: 7,
      details: [
        { label: "声明", value: "2 条" },
        { label: "已使用引用", value: "2 个" },
      ],
      citationIds: ["evidence-1", "brand-1"],
    },
  ],
  metrics: {
    modelSteps: 3,
    toolCalls: 2,
    successfulToolCalls: 2,
    durationMs: 315,
    modelLatencyMs: 279,
    toolLatencyMs: 29,
    inputTokens: null,
    outputTokens: null,
    reasoningTokens: null,
  },
};
